### PR TITLE
fix #515: error: ignoring attributes on template argument 'cl_int {aka int}' 

### PR DESCRIPTION
**Pull request by moneroexamples**
On Arch with gcc 6.1 compilation of ethereum fails do to:

```
/webthree-umbrella/libethereum/libethash-cl/cl.hpp:2423:28: error: ignoring attributes on template argument 'cl_int {aka int}' [-Werror=ignored-attributes]
         VECTOR_CLASS<cl_int>* binaryStatus = NULL,
```

https://github.com/ethereum/webthree-umbrella/issues/515

It can be fixed by adding new pragam to cl.hpp

```
#pragma GCC diagnostic ignored "-Wignored-attributes"
```

### CODE REVIEW

**Comment by bobsummerwill** [comment]
Thanks, @moneroexamples!

See http://52.28.164.97/job/project-build/label=master/4821/.

Looks like the new pragma will need wrapping in some GCC version conditionals, eh?   To avoid breaking earlier GCC versions, like the one we have on our Ubuntu builds.

So I guess it's going to need nested ... "if GCC" and then "if GCC > 6.1.1" or similar?

**Comment by 5chdn** [comment]
Don't want to create a new PR, try:

```
#if __GNUC__ >= 6 
    #pragma GCC diagnostic ignored "-Wignored-attributes" 
#endif
```

...but this would only work on *nix systems I guess.

**Comment by moneroexamples** [comment]
With the `__GNUC__ >= 6` condition proposed by  @5chdn the compilation works fine on Arch and GCC 6.1. 

Should I make a new commit with this change?

**Comment by 5chdn** [comment]
Yes please, let's see if the build server likes this, too :p

**Comment by moneroexamples** [comment]
I close this pull request, as new one with the proposed `__GNUC__ >= 6` condition was created:
https://github.com/ethereum/libethereum/pull/256
